server:
  port: 8084
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost
spring:
  kafka:
    properties:
      sasl:
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required
            username="xc73qeeh" password="OespzQlOp5qKflC4e6Z0KESfrJ510yq5";
        mechanism: SCRAM-SHA-256
      security:
        protocol: SASL_SSL
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      auto-offset-reset: latest
      group-id: xc73qeeh-consumers
      properties:
        spring:
          json:
            trusted:
              packages: sample.kafka
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    bootstrap-servers: tricycle-01.srvs.cloudkafka.com:9094,tricycle-02.srvs.cloudkafka.com:9094,tricycle-03.srvs.cloudkafka.com:9094
cloudkarafka:
  topic: xc73qeeh-default
