product:
  names: [Cuenta Ahorro, Cuenta Corriente, Plazo Fijo, Credito Personal, Credito Empresarial, Tarjeta de Credito Personal, Tarjeta de Credito Empresarial]
  cuentaAhorro:
    maintenance: 0
    monthlyMovements: 10
  cuentaCorriente: 
    maintenance: 20
    monthlyMovements: -1
  plazoFijo:
    maintenance: 0
    monthlyMovements: 1
  creditoPersonal: test
  creditoEmpresarial:
  tarjetaCreditoPersonal:
  tarjetaCreditoEmpresarial:

db:
  connection: connection-string-here
  host: 127.0.0.1
  port: 2800
