server:
  port: 8090
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
      hostname: localhost
      
spring:
  cloud:
    gateway:
      dicovery:
        locator:
          enable: true
      routes:
      - id: client
        uri: http://localhost:8080
        predicates:
        - Path=/client/**
      - id: credit
        uri: http://localhost:8082
        predicates:
        - Path=/credit/**
      - id: account
        uri: http://localhost:8081
        predicates:
        - Path=/account/**
      - id: history
        uri: http://localhost:8086
        predicates:
        - Path=/history/**
      - id: passive-transaction
        uri: http://localhost:8083
        predicates:
        - Path=/passive-transaction/**
      - id: active-withdraw
        uri: http://localhost:8085
        predicates:
        - Path=/active-withdraw/**
      - id: active-payment
        uri: http://localhost:8084
        predicates:
        - Path=/active-payment/**
      - id: report
        uri: http://localhost:8087
        predicates:
        - Path=/report/**
        
