server:
  port: 8086
eureka:
  client:
    fetch-registry: true
    register-eith-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost
spring:
  data:
    mongodb:
      uri: mongodb+srv://rgonzalesm97:JFhtRLmWRJfS2eMA@micluster.tqgdj.mongodb.net/BootcampP1Bank?retryWrites=true&w=majority
  config:
    import: 'optional:configserver:'
